shish/shimmie2

- ext/ouroboros_api/main.php
Now with 17% less fat:
* Moved validation logic into OuroborosPost for sanity
* Added sanity checks for OuroborosPost values
* Changed defaults to be more sane (mainly tags)
* OuroborosPost now accepts an MD5 hash along the metadata (like it
should!)
* Fixed dupe handling logic
See issue #473 for more details.
> Fix duplicate handling

- core/util.inc.php
- ext/qr_code/theme.php
This changes the make_http function to be aware of HTTPS.
Note: I have not tested this change as I currently do not have a site with HTTPS/SSL enabled.
> Change generated links to be aware of HTTPS.

- core/event.class.php
- ext/arrowkey_navigation/main.php
Fix XSS vulnerability in the arrowkey_nav extension.
> Fix XSS in arrowkey extension

- core/imageboard.pack.php
- core/util.inc.php
- ext/bulk_add/main.php
- ext/handle_archive/main.php
- ext/handle_pixel/theme.php
- ext/image/main.php
Remove some more http:// assumptions
> More https

- themes/danbooru/comment.theme.php
- themes/danbooru2/comment.theme.php
- themes/futaba/comment.theme.php
- themes/lite/comment.theme.php
fixes https://github.com/shish/shimmie2/issues/511
> fixed declaration of CustomCommentListTheme::comment_to_html

- ext/chatbox/main.php
:walking:<strike>might cause new bugs checking into this now</strike> or I might not be on a branch with my template .. 
fix chat for relative location.
> hotfix-chatbox-relative-urls

- .htaccess
This requires mod_version installed, but many distributions ship it by default
> Adding support for apache 2.4

- core/imageboard.pack.php
- ext/index/main.php
This speeds up bulk_add when running MySQL < 5.6 (From around 5min > 3s for a batch of 200~ images).
The tags metatag should be a bit more usable now as well (although it still has issues with queries with a lot of possible results, I.E: "tags:>1").
> Subquery optimization on MySQL < 5.6

- core/basethemelet.class.php
- ext/relatationships/main.php
- ext/relatationships/theme.php
This was causing posts to not properly show if they had a child post or not.
> Fix relationships ext checking for TRUE/FALSE instead of Y/N

- core/util.inc.php
- ext/home/main.php
- ext/home/theme.php
- ext/ipban/main.php
- themes/danbooru/layout.class.php
- themes/danbooru2/layout.class.php
- themes/default/layout.class.php
- themes/futaba/layout.class.php
- themes/lite/layout.class.php
- themes/material/layout.class.php
- themes/warm/layout.class.php
some people have mailto: already, and some want non-mail contact links
> Have contact_link support http: and mailto:

- ext/index/test.php
- tests/bootstrap.php
Adding some more tests so that we can see that #548 has fixed the issues
> Search tests

- ext/blotter/script.js
- ext/handle_pixel/script.js
- ext/index/script.js
- ext/pools/script.js
- ext/tagger/script.js
- lib/jquery.cookie-1.4.0.min.js
- lib/js.cookie.js
- lib/shimmie.js
all of shimmie's JS libraries are horrifically out of date D:
> migrate to a non-deprecated (and dependency-free) cookie library

- core/page.class.php
- ext/home/theme.php
- ext/site_description/test.php
- themes/danbooru/layout.class.php
- themes/danbooru2/layout.class.php
- themes/default/layout.class.php
- themes/futaba/layout.class.php
- themes/lite/layout.class.php
- themes/material/home.theme.php
- themes/material/layout.class.php
- themes/warm/layout.class.php
this function was defined, but apparently not used ._.
> fix and use get_all_html_headers()

- composer.lock
Just seeing if this helps
https://scrutinizer-ci.com/g/shish/shimmie2/inspections/68bab58b-9038-4a01-b032-fcd8490cc657
> add composer.lock for scrutinizer-ci

- .travis.yml
- README.markdown
- ext/artists/main.php
- ext/autocomplete/script.js
- ext/autocomplete/style.css
- ext/ext_manager/theme.php
- ext/link_image/theme.php
- ext/pools/theme.php
- ext/tagger/script.js
- lib/shimmie.js
Few small fixes/changes here.
* Made it more clear to what extensions have docs by moving the link to a separate column.
* Added Scrutinizer Code Quality & Code Coverage buttons to the README.
* Cleaned up the wording of the instructions for "Installation (Development)".
* Some scrutinizer recommended fixes.
* Travis now allows SQLite to fail (since it's experimental). Also disabled all the failure logs since they don't work on the new container infrastructure.
* Basic metatag support for autocomplete.
> Few small fixes/changes

- .htaccess
- ext/upload/main.php
This cleans up a few superficial errors
> Clean up a few superficial errors

- ext/chatbox/history/index.php
- ext/chatbox/php/functions.php
This fixes the XSS issue identified in #597.
> #597: Fix for XSS issue in chatbox extension.

- ext/bulk_add_csv/main.php
> bulk_add_csv: Run Tag::explode() on the tags

- ext/handle_archive/main.php
> Fix issue with archive handler if there is no add_status() method for the theme

- core/config.php
- core/imageboard/image.php
- ext/cron_uploader/main.php
- themes/danbooru/themelet.class.php
- themes/danbooru2/themelet.class.php
- themes/futaba/themelet.class.php
- themes/lite/themelet.class.php
Fixed an issue when null queries were passed to some themes. Just needed the parameter specs changed to allow nulls.
>  Fixes for various issues

- core/util.php
Implements what's proposed in #656
> Path to tags enhancements

- core/imageboard/image.php
now that the accurate search doesn't use subqueries, perhaps mysql can accept it?
> Remove build_ugly_search_querylet

- core/permissions.php
- core/userclass.php
- core/util.php
- ext/cron_uploader/config.php
- ext/cron_uploader/main.php
- ext/cron_uploader/style.css
- ext/cron_uploader/theme.php
I implemented a few of the to-dos and buffed up the overall security and reliability of the process
> Cron upload

- core/permissions.php
- core/polyfills.php
- core/userclass.php
- ext/approval/info.php
- ext/approval/main.php
- ext/approval/theme.php
- ext/help_pages/main.php
- ext/rating/main.php
- ext/upload/main.php
- themes/danbooru2/ext_manager.theme.php
- themes/danbooru2/view.theme.php
Another batch of changes and fixes for you to consider
> Various changes

- themes/futaba/themelet.class.php
Same issue and fix as #699, I just forgot to check this theme~
> Fix Futaba theme with new strict types

- ext/tag_editcloud/main.php
I'm hoping for this to serve as a starting point for a better implementation.
This change implements a simple **category-based alphabetical tag sorting** system that puts all tags containing ':' in front of general tabs. It also groups them together for easier styling into columns, grids, or even opening the door for drop-down categories in the edit menu. A much needed feature for me since I have hundreds of tags and I manage them all by my own.
Both features can be easily implemented on their own, although it's just a single commit because the styling feature only really benefits from category sorting (unless someone has a better idea for it).
EDIT: Haven't put my credits on it. I didn't feel like sticking my name on the side of someone that has made the entire extension on their own :P …
> Tag EditCloud: Added category sorting and grouped tags.

- core/command_builder.php
- core/imageboard/image.php
- ext/handle_video/main.php
- ext/media/main.php
- ext/media/video_codecs.php
- ext/transcode/main.php
- ext/transcode_video/config.php
- ext/transcode_video/info.php
- ext/transcode_video/main.php
- ext/transcode_video/script.js
- ext/transcode_video/theme.php
- themes/lite/view.theme.php
Right now it just handles container transformation, which allows getting mkv with vp8/vp9 to webm or anything with h264 to an mp4 container, allowing them to be played back in-browser.
> Video transcoding

- core/imageboard/image.php
- core/install.php
- ext/upgrade/main.php
An attempt at updating all the code to use BOOLEAN instead of having a mixture of `BOOLEAN` / `CHAR(1)` / `ENUM("Y", "N")`
> [WIP] Use SQL booleans

- ext/tag_list/config.php
- ext/tag_list/main.php
- ext/tag_list/theme.php
It seemed strange that this wasn't a feature. I love both options so I made it :)
> Option to display post tags and related tags at the same time

- ext/bbcode/info.php
I had to look through the code to find the tags I wanted, so here they are.
Probably still missing a few, tho.
> Add missing entries in bbcode docs

- core/basepage.php
I have multiple CSS files on my theme and I wanted them to be part of the cache system :) Is this good enough?
> CSS and JS files configurable by themes

- ext/handle_pixel/theme.php
bug introduced in e82b9ea811
should fix #825, #836
> Add missing quote in html returned by handle_pixel theme

- core/imageboard/image.php
This updates the `Image` class to permit setting `posted` before the item is committed to the database.
This allows for backdating (or, of course, forward-dating) uploads in custom extensions. An example of taking advantage of this is [in our fork](https://github.com/friends-of-the-core/shimmie2/blob/a1eb45ede98f1de8cec50c2618b32d70f1d98262/ext/filename_metadata/main.php) where we are ultimately taking the post time information (and user information) from a Discord channel.
I believe there may be a bug here preventing this from working with MySQL backends; I've only fully tested this against SQLite (which doesn't care) and Postgres (which perfectly accepts this date format). If you've got any hints for this, let me know!
Additionally, I added the ability to set the uploader in the same …
> Allow pre-setting `$image->posted` values

- ext/auto_tagger/main.php
- ext/pools/main.php
- ext/pools/theme.php
Tool if you added your images to a pool in the inverse order
> Pool - Reverse function

- themes/default/style.css
> [themes/default] dark mode, see #937

- composer.json
- composer.lock
- core/basethemelet.php
- core/microhtml.php
- ext/artists/theme.php
- ext/image_view_counter/main.php
- ext/post_titles/theme.php
- ext/rating/main.php
- ext/rating/theme.php
- ext/relationships/theme.php
- ext/rule34/main.php
- ext/tag_edit/theme.php
- ext/tag_editcloud/main.php
- ext/view/events/image_info_box_building_event.php
- ext/view/main.php
for consistency in the info box
> SHM_POST_INFO element

- core/urls.php
- ext/approval/main.php
- ext/comment/theme.php
- ext/image/main.php
- ext/private_image/main.php
- ext/rating/main.php
- ext/regen_thumb/main.php
- ext/trash/main.php
- ext/user/main.php
if you want just a default page, leave it empty
> only link to post/list when you actually want post/list

- themes/danbooru2/themelet.class.php
> [themes/danbooru2] adjust rules for when to show '...'

- ext/relationships/theme.php
- themes/danbooru2/view.theme.php
Fix parent-id type issue
Fix extra search button in theme
> Remove redundant button

- .devcontainer/devcontainer.json
- .gitignore
- Dockerfile
Getting xdebug working on osx is a pain, devcontainers are less pain...
> Basic devcontainer setup

- .devcontainer/devcontainer.json
- core/install.php
Made some changes using codespaces
> Codespace-test

- core/tests/SearchTest.php
[core] test for order=random_1234
> [core] test for order=random_1234

- core/polyfills.php
- core/tests/PolyfillsTest.php
- ext/comment/theme.php
- ext/forum/theme.php
- themes/danbooru/comment.theme.php
- themes/danbooru2/comment.theme.php
- themes/futaba/comment.theme.php
[core] test truncate() properly, and then fix it, and then use it
> [core] test truncate() properly, and then fix it, and then use it

- .devcontainer/devcontainer.json
- .docker/entrypoint.d/config.json.tmpl
- .docker/entrypoint.sh
- Dockerfile
[docker] accept MAX_FILE_UPLOADS as a docker environment variable
> [docker] accept MAX_FILE_UPLOADS as a docker environment variable

- .docker/entrypoint.sh
[docker] only replace specific variables, fixes #1064
> [docker] only replace specific variables, fixes #1064

- .devcontainer/devcontainer.json
- .docker/run.php
[devcontainer] fix user creation
> [devcontainer] fix user creation

- .github/workflows/tests.yml
[ci] run tests in dev mode, with assertions
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/shimmie2/pull/1071).
* #1072
* __->__ #1071
> [ci] run tests in dev mode, with assertions

- .devcontainer/bash_history
- .devcontainer/devcontainer.json
[devcontainer] seed shell history
> [devcontainer] seed shell history

- ext/index/main.php
- ext/media/main.php
- ext/post_source/main.php
- ext/post_tags/main.php
[various] split Index::onSearchTermParse into relevant extensions
> [various] split Index::onSearchTermParse into relevant extensions

- ext/handle_archive/main.php
[handle_archive] standard tmpdir
> [handle_archive] standard tmpdir

- ext/setup/main.php
[setup] don't crash if multichoice isn't set
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/shimmie2/pull/1073).
* #1075
* #1074
* __->__ #1073
> [setup] don't crash if multichoice isn't set

- core/tests/UserClassTest.php
- core/userclass.php
- ext/setup/main.php
[core] UserClass tests
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/shimmie2/pull/1074).
* #1075
* __->__ #1074
* #1073
> [core] UserClass tests

- ext/home/style.css
> Wrap nav links on home page to prevent overflow on small screen sizes

- core/imageboard/search.php
- ext/index/main.php
Mostly I want a simple way to compare the before-and-after of #1082 👀
`php index.php debug:search 'cake -test'`
`SELECT images.* FROM images INNER JOIN (SELECT DISTINCT it.image_id FROM image_tags it LEFT JOIN image_tags negative ON negative.image_id = it.image_id AND negative.tag_id IN (80) WHERE it.tag_id = 2 AND negative.image_id IS NULL GROUP BY it.image_id ) a on a.image_id = images.id ORDER BY images.id DESC LIMIT 25 OFFSET 0`
> [core] search code docs and test function

- ext/not_a_tag/main.php
> [not_a_tag] fix link

- ext/image_hash_ban/main.php
> [image_hash_ban] fix link

- themes/default/style.css
[themes/default] nicer table headings
> [themes/default] nicer table headings

- core/imageboard/image.php
- ext/graphql/test.php
- ext/image/main.php
[graphql] fix graphql field access, fixes #1089
> [graphql] fix graphql field access, fixes #1089

- composer.json
- composer.lock
> [deps] bump gqla

- core/imageboard/image.php
- ext/graphql/main.php
- ext/graphql/test.php
[graphql] custom field resolver, fixes #1089
> [graphql] custom field resolver, fixes #1089

- .github/CONTRIBUTING.md
- .github/workflows/tests.yml
- composer.json
> [ci] test shortcuts

- .docker/run.php
[docker] set php.ini variables in a flexible way, see #1096
> [docker] set php.ini variables in a flexible way, see #1096

- .docker/run.php
[docker] fix max filesize / max uploads being counted wrong
> [docker] fix max filesize / max uploads being counted wrong

- ext/tag_categories/theme.php
[tag_categories] send a CSRF token along with tag category edits, fixes #1103
> [tag_categories] send a CSRF token along with tag category edits, fixes #1103

- ext/tag_categories/main.php
[tags] redirect to view page after updating tags, fixes #1103
> [tags] redirect to view page after updating tags, fixes #1103

- ext/tag_categories/theme.php
- ext/tag_list/main.php
- ext/tag_list/test.php
[tags] fully separate tag_list and tag_categories, see #1103
> [tags] fully separate tag_list and tag_categories, see #1103

- ext/s3/main.php
[s3] sync by query (which might be an ID range) rather than by ID range
> [s3] sync by query (which might be an ID range) rather than by ID range

- ext/admin/main.php
- ext/regen_thumb/main.php
[regen-thumb] have regen-thumb ext handle the regen-thumb command
> [regen-thumb] have regen-thumb ext handle the regen-thumb command

- ext/notes/script.js
> [notes] Round note dimensions to int

- core/event.php
- ext/comment/main.php
- ext/favorites/main.php
- ext/forum/main.php
- ext/help_pages/main.php
- ext/image/main.php
- ext/numeric_score/main.php
- ext/report_image/theme.php
- ext/user/events.php
- ext/user/main.php
- ext/user/theme.php
- ext/user_config/main.php
- ext/user_config/theme.php
- ext/view/events/image_admin_block_building_event.php
- ext/view/events/image_info_box_building_event.php
- ext/view/main.php
Have a common PartListBuildingEvent, fixes #1124
> Have a common PartListBuildingEvent, fixes #1124

- ext/filter/info.php
- ext/filter/main.php
- ext/filter/script.js
- ext/filter/style.css
- ext/filter/theme.php
- themes/danbooru/index.theme.php
- themes/danbooru2/index.theme.php
This extension is derived from Danbooru's blacklist code, which runs as client-side JS.
Admins can set default tags and users can override them.
Closes https://github.com/shish/shimmie2/issues/245
> [filter] add filter extension

- ext/featured/main.php
- ext/featured/test.php
> [featured] fix feature button

- ext/rss_images/main.php
[rss_images] fix page matching
> [rss_images] fix page matching

- ext/rating/theme.php
- ext/wiki/theme.php
> [wiki] fixes

- ext/blocks/main.php
[blocks] 'delete' param isn't required
> [blocks] 'delete' param isn't required

- README.md
[docs] remove scrutinizr links
> [docs] remove scrutinizr links

- ext/statsd/main.php
[statsd] group by starts_with, not matches
> [statsd] group by starts_with, not matches

- core/event.php
[core] make PageRequest->page_starts_with be less weird
> [core] make PageRequest->page_starts_with be less weird

- .devcontainer/devcontainer.json
[dev] postStartCommand rather than postCreateCommand for running the service
> [dev] postStartCommand rather than postCreateCommand for running the service

- core/user.php
- ext/bulk_actions/main.php
- ext/pools/main.php
- ext/transcode/main.php
- ext/user/main.php
[core] remove is_logged_in
This was only used in a couple of places, and user classes are more useful
> [core] remove is_logged_in

- themes/danbooru2/user.theme.php
[danbooru2] minor fixes for signup form
> [danbooru2] minor fixes for signup form

- core/basepage.php
- ext/autocomplete/script.js
- ext/notes/script.js
- ext/static_files/init.js
[core] add shm_make_link JS function, to generate links from JS which work both with and without niceurls, fixes #1160, fixes #1151
> [core] add shm_make_link JS function, to generate links from JS which work both with and without niceurls, fixes #1160, 

- ext/terms/style.css
- ext/terms/theme.php
> [terms] implement terms and conditions blur modal, fixes #1166

- core/testcase.php
[core] make request cookies configurable
> [core] make request cookies configurable

- ext/terms/test.php
[terms] add tests
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/shimmie2/pull/1171).
* #1169
* __->__ #1171
> [terms] add tests

- ext/terms/main.php
- ext/terms/test.php
[terms] allow users to view wiki pages before accepting the terms that are written in the wiki
> [terms] allow users to view wiki pages before accepting the terms that are written in the wiki

- ext/blocks/info.php
Clarifies behaviour, see https://github.com/shish/shimmie2/pull/926
> [blocks] add documentation

- ext/setup/main.php
- ext/user_config/main.php
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/shimmie2/pull/1184).
* #1185
* __->__ #1184
> [setup] have ConfigSaveEvent save the config

- core/database.php
- core/dbengine.php
- core/user.php
- ext/tagger_xml/main.php
> [core] use || for SQL concatenation

- core/install.php
- core/sys_config.php
- core/user.php
- tests/defines.php
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/shimmie2/pull/1195).
* #1199
* __->__ #1195
> [core] have a system level SECRET variable, to be used as a salt separate from DATABASE_DSN

- core/util.php
- ext/index/main.php
[core] add PetalBot to the list of bots
> [core] add PetalBot to the list of bots

- Dockerfile
[docker] add rsync for backups
> [docker] add rsync for backups

- core/basepage.php
- core/config.php
- core/database.php
- core/extension.php
- core/polyfills.php
- core/testcase.php
- core/urls.php
- core/user.php
Make some more things null-safe
(in preparation for bumping up the phpstan strictness to disallow null-unsafe code)
> Make some more things null-safe

- ext/setup/main.php
- ext/user/events.php
- ext/user_config/main.php
people who need Configs should accept Configs, no need to specify BaseConfig
> people who need Configs should accept Configs, no need to specify BaseConfig

- core/config.php
[core] merge Config and BaseConfig
Multiple layers of inheritance were confusing both humans and tools...
> [core] merge Config and BaseConfig

- core/block.php
- core/database.php
- core/imageboard/tag.php
- core/polyfills.php
- core/send_event.php
- core/stdlib_ex.php
- ext/bbcode/main.php
- ext/emoticons/main.php
- ext/et/main.php
- ext/image/main.php
- ext/index/main.php
- ext/media/main.php
- ext/static_files/main.php
- ext/upload/main.php
- ext/user/theme.php
- ext/user_config/theme.php
- ext/word_filter/main.php
- themes/futaba/comment.theme.php
Add preg_replace_ex
having preg_replace return string|array|null is a pain, string|exception is much cleaner
> Add preg_replace_ex

- core/basepage.php
- core/block.php
- ext/graphql/test.php
- ext/image_hash_ban/main.php
- ext/index/main.php
- ext/ipban/test.php
- ext/link_image/theme.php
- ext/log_db/main.php
- ext/ouroboros_api/main.php
- ext/pools/main.php
- ext/pools/theme.php
- ext/post_source/main.php
- ext/random_image/test.php
- ext/rating/test.php
- ext/ratings_blur/test.php
- ext/s3/main.php
- ext/user/events.php
- ext/user/main.php
- ext/user_config/main.php
- ext/user_config/theme.php
- ext/word_filter/main.php
- tests/phpstan.neon
- themes/lite/page.class.php
[dev] bump phpstan strictness
no more null surprises
> [dev] bump phpstan strictness

- composer.lock
bump eventtracer dep for php8.4 compat
> bump eventtracer dep for php8.4 compat

- core/basepage.php
- core/block.php
- core/cli_app.php
- core/config.php
- core/imageboard/misc.php
- core/testcase.php
- core/tests/SearchTest.php
- core/userclass.php
- ext/bulk_actions/main.php
- ext/forum/theme.php
- ext/index/events.php
- ext/media/events.php
- ext/media/main.php
- ext/ouroboros_api/main.php
- ext/pools/main.php
- ext/post_source/theme.php
- ext/rating/main.php
- ext/setup/main.php
- ext/wiki/main.php
no implicit nulls (they are deprecated in php8.4)
> no implicit nulls (they are deprecated in php8.4)

- ext/setup/main.php
- ext/setup/test.php
- ext/user_config/main.php
[settings] postToSettings
Trying to keep the weird POST-formatting to a minimum, using real types where possible
> [settings] postToSettings

- composer.lock
> ffsphp-bump

- core/database.php
make sure stdlib_ex is included before database things, fixes #1240
> make sure stdlib_ex is included before database things, fixes #1240

- core/urls.php
add even more hacks onto the pile of hacks for URL parsing, see #1236
> add even more hacks onto the pile of hacks for URL parsing, see #1236

- core/tests/UrlsTest.php
- core/urls.php
add another special case for URL parsing, and some tests, see #1236
> add another special case for URL parsing, and some tests, see #1236

- core/polyfills.php
don't assume exception messages are html
> don't assume exception messages are html

- core/basepage.php
- themes/danbooru/page.class.php
- themes/danbooru2/page.class.php
- themes/futaba/page.class.php
- themes/lite/page.class.php
- themes/warm/page.class.php
factor out commonly duplicated flash_html
> factor out commonly duplicated flash_html

- core/basepage.php
- core/util.php
> footer_html as HTMLElement

- core/testcase.php
[core] clean Page for each unit test
> [core] clean Page for each unit test

- core/basepage.php
- core/block.php
- core/tests/BlockTest.php
- ext/downtime/theme.php
- ext/emoticons_list/theme.php
- ext/home/main.php
- ext/home/theme.php
- themes/danbooru/page.class.php
- themes/danbooru2/page.class.php
- themes/futaba/page.class.php
- themes/lite/page.class.php
- themes/warm/page.class.php
> body_html as htmlelement

- core/basethemelet.php
- core/exceptions.php
- core/imageboard/image.php
- ext/alias_editor/main.php
- ext/artists/main.php
- ext/auto_tagger/main.php
- ext/ext_manager/main.php
- ext/image_hash_ban/test.php
- ext/index/test.php
- ext/index/theme.php
- ext/numeric_score/test.php
- ext/pm/main.php
- ext/pools/test.php
- ext/random_image/main.php
- ext/upload/main.php
- ext/user/main.php
- ext/user/test.php
- ext/view/main.php
- ext/view/test.php
- themes/danbooru2/index.theme.php
[core] throw exceptions rather than display_error
> [core] throw exceptions rather than display_error

- core/basethemelet.php
- ext/image_hash_ban/main.php
- ext/log_db/main.php
- ext/not_a_tag/main.php
- ext/user/main.php
> remove display_crud

- core/block.php
- ext/comment/main.php
- ext/help_pages/main.php
- ext/image_hash_ban/main.php
- ext/log_db/main.php
- ext/media/main.php
- ext/mime/main.php
- ext/not_a_tag/main.php
- ext/notes/main.php
- ext/numeric_score/main.php
- ext/private_image/main.php
- ext/relationships/main.php
- ext/tag_categories/main.php
- ext/trash/main.php
- ext/user/main.php
Move away from creating empty Blocks and then adding properties later
Things can happen in __construct o.o
> Move away from creating empty Blocks and then adding properties later

- .github/workflows/tests.yml
> readd arm64

- ext/autocomplete/script.js
- ext/index/events.php
- ext/index/main.php
- ext/index/test.php
- themes/danbooru/index.theme.php
- themes/danbooru2/index.theme.php
generic operand support
We're already special-casing `-` for NOT, there is a PR for special-casing `~` for OR, it'd be nice to have a general system rather than multiple special cases
> generic operand support

- ext/tag_editcloud/main.php
fix tag edit cloud sort-by-relevance, fixes #1265
> fix tag edit cloud sort-by-relevance, fixes #1265

- .github/workflows/tests.yml
- composer.json
- composer.lock
- ext/resize/main.php
- ext/rotate/main.php
> php8.4 support

- tests/router.php
> re-add tests/router.php

- core/util.php
- ext/source_history/main.php
- ext/tag_history/main.php
ignore invalid IPs rather than crashing, see #1221
> ignore invalid IPs rather than crashing, see #1221

- ext/et/main.php
- ext/et/theme.php
add extra info to /system_info to help debugging #1221
> add extra info to /system_info to help debugging #1221

- ext/post_peek/script.js
[post_peek] be compatible with niceurls, see #1280
> [post_peek] be compatible with niceurls, see #1280

- tests/router.php
also serve png/ico/svg files raw, if they exist
> also serve png/ico/svg files raw, if they exist

- .github/workflows/tests.yml
- composer.json
- tests/phpstan.neon
different error formats for phpstan CI vs local
> different error formats for phpstan CI vs local

- ext/pools/theme.php
Referenced in this issue https://github.com/shish/shimmie2/issues/1292
> Fix private pool creation - Pool Extension

- .php-cs-fixer.dist.php
disable php-cs-fixer parallelism since it breaks phpactor
> disable php-cs-fixer parallelism since it breaks phpactor

- core/database.php
[core] return types for Database::get_*_iterable
> [core] return types for Database::get_*_iterable

- core/database.php
[core] fix case of PDO::rollBack()
> [core] fix case of PDO::rollBack()

- ext/danbooru_api/info.php
[danbooru_api] remove redundant docs
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/shimmie2/pull/1298).
* #1299
* __->__ #1298
> [danbooru_api] remove redundant docs

- ext/danbooru_api/main.php
[danbooru_api] various fixes, fixes #1209
> [danbooru_api] various fixes, fixes #1209

- core/util.php
- ext/eokm/main.php
- ext/replace_file/main.php
- ext/upload/main.php
phpstan 2.0 types these better
> Fix curl_setopt types

- ext/common_elements/theme.php
- ext/tag_categories/main.php
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/shimmie2/pull/1347).
* #1348
* __->__ #1347
> [tag_categories] more consistent naming

- composer.json
- composer.lock
upstream is alive again, v3 contains the fixes from `shish/safe`
> Switch to thecodingmachine/safe v3

- ext/post_source/main.php
- ext/post_tags/main.php
> [post_tags/source] put tag search in tags and source search in source

- ext/user/main.php
no need to display this popup when viewing someone else's profile, i forgot to add this check before.
> [avatars] only display "no avatar?" popup on your own profile page

- core/config_group.php
- ext/ban_words/config.php
- ext/blotter/config.php
- ext/bone_quality/config.php
- ext/bulk_download/config.php
- ext/common_elements/theme.php
- ext/custom_html_headers/config.php
- ext/downtime/config.php
- ext/filter/config.php
- ext/home/config.php
- ext/image/config.php
- ext/ipban/config.php
- ext/media/config.php
- ext/terms/config.php
- ext/transcode/config.php
- ext/upload/config.php
- ext/user/config.php
- ext/wiki/config.php
- ext/word_filter/config.php
having a snakecase parameter among the single simple words felt weird...
> [core] s/ui_type/input/

- core/User/User.php
- core/User/UserClass.php
- ext/comment/theme.php
- ext/perm_manager/main.php
- ext/pm/theme.php
- ext/rating/config.php
- ext/statistics/main.php
- ext/user/main.php
- ext/user/permissions.php
this approach is hacky and inefficient and it makes unrelated parts of the code unnecessarily complicated - if people want the feature, we can come up with a new implementation
> [misc] remove support for hellbans

- ext/wiki/main.php
- ext/wiki/style.css
- ext/wiki/theme.php
I think mentioned like this in #1423, simply a wiki page that lists all existing pages
> [wiki] List all wiki pages

- core/Page/Page.php
How long does rendering take? :eyes:
> [core] trace page display

- ext/pools/main.php
The add pool option in image admin didn't work because there was no handler
> [pools] add_pool was missing a handler

- ext/handle_ico/main.php
unit tests currently shouldn't depend on external commands
> [handle_ico] static thumbnails for unit tests

- core/Config/DatabaseUserConfig.php
- core/User/User.php
- index.php
- tests/bootstrap.php
The amount of complexity to support two usecases is greater than the complexity in the class itself...
> [core] split DatabaseConfig and DatabaseUserConfig into two classes

- ext/perm_manager/main.php
- ext/user/main.php
- ext/user_class_file/info.php
- ext/user_class_file/main.php
> [permissions] split default, file-based, and database-based UserClasses into three separate exts that can be enabled or 

- core/Page/Page.php
- core/Page/Page_Data.php
- core/Page/Page_Error.php
- core/Page/Page_File.php
- core/Page/Page_Page.php
- core/Page/Page_Redirect.php
- core/Page/README.md
- core/Page/WithFlash.php
- core/Util/util.php
- ext/alias_editor/main.php
- ext/auto_tagger/main.php
- ext/bulk_download/main.php
- ext/bulk_import_export/main.php
- ext/image/main.php
Page is getting huuuuuuuge, and it does several _almost_ completely-unrelated things
> [core] split Page behaviour into several traits

- core/Util/Installer.php
- ext/media/config.php
- ext/media/main.php
- ext/transcode/main.php
ImageMagick has decided to deprecate the `convert` command and get everybody to use `magick`
> [media] s/convert/magick/

- ext/notes/theme.php
- Process entries similarly to source history page for consistency
- Convert the revert hyperlink to a submit button. This prevents crawlers from visiting the revert handler if anonymous users are given note editing permissions.
- Rename "Revert" to "Revert To" for clarity (and correctness)
- Remove revert button from most recent version for clarity and to avoid generating identical redundant revisions
- Fix broken link to a note's history page
- Fix broken table formatting in actions columns
> [notes] various improvements to note history page

- ext/handle_pixel/main.php
- ext/handle_pixel/script.js
- ext/handle_pixel/style.css
- ext/handle_pixel/theme.php
- ext/notes/script.js
- ext/notes/style.css
Always was annoyed by click to zoom not actually zooming to the location clicked, so tried to improve on it
> [handle_pixel] improved click-to-zoom and resizing

- ext/handle_pixel/script.js
noticed old redundant code, and the logic when the image is smaller than the window was flawed
> [handle_pixel] js code cleanup and logic fix

- ext/reverse_search_links/main.php
did not function anymore, now does
> [reverse_search_links] fix mime

- ext/notes/script.js
having them be a fixed 100px wide can make them tiny if the post is huge and zoomed out
> [notes] make new notes be a fraction of the post size

- ext/notes/main.php
in case there's any whitespace for some weird reason
> [notes] trim IP addresses when converting
