- core/util.inc.php
- ext/tag_edit/theme.php
- ext/upload/main.php
This pull request is a minor change that fixes the warnings issue (reported in #487) and also fixes the auto-complete for the tag edit box (reported in #489).
```
Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/xxx/public_html/core/util.inc.php on line 1004
Warning: array_change_key_case() expects parameter 1 to be array, boolean given in /home/xxx/public_html/core/util.inc.php on line 1007
Warning: array_key_exists() expects parameter 2 to be array, null given in /home/xxx/public_html/core/util.inc.php on line 1008
Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/xxx/public_html/core/util.inc.php on line 1004
Warning: array_change_key_case() expects parameter 1 to be array, boolean given in …
```
> Only examine response headers if we actually have them & remove duplicate 'class' attribute.

- core/database.class.php
- core/exceptions.class.php
- core/imageboard.pack.php
- core/user.class.php
- core/util.inc.php
- ext/user/main.php
Replacing a whole bunch of boilerplate code with minimal error handling (if input is invalid, die silently) with much less code plus user-friendly(...ish) error messages
```
if(is_set($_POST['user_id'])) {
$user_id = $_POST['user_id'];
$user = User::by_id($user_id);
if(is_null($user)) {
error_message("invalid user id");
}
[... do stuff with $user...]
}
else {
error_message("missing input");
}
```
to
```
$input = validate_input(array(
'user' => 'user_id,exists,to_object',
));
[...do stuff with $input['user']...]
```
> validate_input() function

- core/imageboard.pack.php
- core/util.inc.php
- ext/bulk_add/main.php
- ext/pools/theme.php
This should fix the issue in #505.
Bulk_Add no longer gets stuck in loop when checking for subdirectory & properly notifies the user if files don't exist in directory or directory doesn't exist, rather than showing no handler exist error.
Two other minor fixes included:
* Negative aliases should properly convert each aliased tag to negative, rather than just the first tag.
* Pools index link was throwing JS errors as was also being used as ID, using specified ID fixes this.
> Fixes #505 & other small fixes

- ext/notes/main.php
By default, the notes extension doesn't work with an SQLite database. Throws an error about `LAST_INSERT_ID()` not existing when you try to add a note. This PR just makes it use the equivalent SQLite function there.
It looks like Postgres would probably need something different again there. I'm not familiar with it though, so I just left it alone.
> Fix the notes extension to work properly on SQLite

- core/block.class.php
Example problem is ext/blotter uses:
$page->add_block(
new Block(
"Welcome to the Blotter Editor!", <-- SEE --> !
$html, "main", 10));
> Hotfix block id character stripping

- core/imageboard.pack.php
- ext/numeric_score/main.php
- ext/relatationships/main.php
- ext/tag_edit/main.php
- ext/user/main.php
This should help any extension which uses onTagSet. Proper tags are now sent, and metatags are not.
Other things:
* Minor speed tweaks, which is mainly avoiding looping over possible duplicate tags & doing a simple pre-check to see if a tag could be a metatag (rather than running the tag through 10~ preg_match).
* resolve_aliases should now use Tag::explode instead of explode. This fixes a rare case where an empty tag could be passed.
> Move tag sanitization, alias resolving & tag parsing from set_tags > TagSetEvent

- ext/bulk_add/main.php
- ext/bulk_add/theme.php
The bulk add screen was having errors resulting from the block handling of the page. This allows the results to display on my system.
> Fixes for bulk add results

- core/imageboard.pack.php
This fixes two wildcard tag bugs:
* Fixes single-tag wildcard searches returning duplicate results if the image has more than one match.
* Fixes multi-tag wildcard searches not returning the correct results if wildcard tag has more than one match on the image.
> Fix wildcard tag bugs

- ext/handle_video/main.php
Regenerate thumbnail doesn't work since the output file already exists and ffmpeg expects the user to decide wether to replace the file or not. With the -y switch set, ffmpeg does so without asking.
https://ffmpeg.org/ffmpeg.html#Main-options
> Set ffmpeg's "overwrite output files" switch (-y)

- core/imageboard.pack.php
- core/util.inc.php
see #547
The general approach here is to keep wildcards in their wildcard form until as late as possible, so that the searching function can treat them specially (as opposed to expanding them at the start and then having no idea which tags were requested and which are part of a wildcard expansion)
> re-fix wildcards for mysql

- ext/upload/bookmarklet.js
- ext/upload/main.php
- ext/upload/theme.php
This should fix some of the issues with bookmarklets.
- Importing from another Shimmie was and still is troublesome. It still has difficulty with videos and ratings in this regard, from what I've tested.
- If the source is using HTTPS, then the destination will have to as well. Otherwise it won't work in most popular browsers due to mixed content errors. It's recommended that the destination be using HTTPS for the highest compatibility.
- A few sites still don't work due to hotlink protection.
> Fix bookmarklets

- ext/handle_video/main.php
- ext/handle_video/theme.php
This patch adds a board config block for video playback options.
Two new options are available:
- Autoplay (default = true)
- Loop* (default = true)
It works with the HTML5 player and _probably_ with the Flash player. I haven't been able to test the latter because it doesn't work at all for me on the develop branch.
\* This makes looping the default again (a0a39784d42fe02ba63b6c1a3e631352539313b2). The move from Jaris to MediaElement (b0daab87662adf130ebca9a3f9efe24c0dd44cfd) had disabled it.
> Added video playback options for autoplay and loop

- core/basethemelet.class.php
- ext/tag_list/theme.php
This fixes an issue where tags were not always escaped, allowing for code injection.
Try adding this tag to a post, then view it in the post list:
`'><script>alert("BOO!");</script>`
> Fix tags not being escaped for HTML in some cases (code injection vulnerability)

- ext/tag_list/main.php
This fixes the "starts-with" headers* on the tags/alphabetic page. Before, the headers would be wrong if they started with an escaped character.
This also escapes the resulting header so that it no longer generates invalid HTML in such cases.
\* Note that these headers are only visible when paged tag lists is disabled.
> Fix "starts-with" header in tag list when escaping required

- ext/pools/theme.php
Fixes a code injection vulnerability where pool descriptions were allowed to have arbitrary HTML in them.
For reference, try using this as a pool description:
`<script>alert("BOO!");</script>`
It should be noted that I only guessed at this solution based on what the comments extension does. It seems to work, though.
> Update pool description formatter (code injection vulnerability)

- ext/mass_tagger/script.js
- ext/mass_tagger/style.css
- Clear selected images on load in case they were autocompleted by the browser.
- Otherwise you could end up with images that were selected but didn't have the selection effect.
- Use CSS for mass tagger button styling
- Uses the class name `mass-tagger-selected`
- Makes it easier to style the selection effect
> Mass tagger fixes

- ext/handle_ico/main.php
Zero width / height should be interpreted as 256 (source: https://en.wikipedia.org/wiki/ICO_(file_format)#Outline).
> Fix .ico when size is 256 x 256

- ext/pools/theme.php
This change replaces the "Index" block on the pool pages with a generic NavBlock.
The reason for this change is twofold:
1. It's more consistent with the other pages
2. It fixes a javascript error that can occur when using the lite theme
To expand upon number 2:
A javascript error occurs under the following conditions:
- You are using the lite theme
- You visit any of the pool pages
Here's a rundown of why this happens:
1. The lite theme is set to create a shm-toggler out of each block in the sidebar ([themes/lite/layout.class.php#L225](https://github.com/shish/shimmie2/blob/3051334d8f153862a3e1b1a6de65c08b31ede52d/themes/lite/layout.class.php#L225)). The shm-toggler must have an anchor to work with, so it generates one from the block's title.
2. However, there is one problem with doing …
> Use generic NavBlock on pool pages (fixes a JS error)

- core/util.inc.php
- ext/comment/theme.php
- ext/tag_editcloud/main.php
- themes/danbooru/comment.theme.php
- themes/danbooru2/comment.theme.php
- themes/futaba/comment.theme.php
This fixes a JS code injection vulnerability that affected the "delete comment" dialog. By using a crafted comment, it was possible to inject a small amount of Javascript (~50 characters) to be executed whenever a user tries to delete an affected comment.
Below are examples of crafted comments and the effects they would have without this fix.
```
')&&alert('BOO!
```
```
')==('
```
```
hitler did nothn wrong[align=right]')==('[/align]
```
In order to correctly escape the strings used in the JS-based comment deletion prompt, it was necessary to unescape the result of the TextFormattingEvent because it had already been escaped for HTML. While doing so felt a little dirty, there was no other way besides making deeper changes.
> Fix comment-delete injection

- .htaccess
- ext/handle_ico/main.php
- ext/handle_ico/test.php
- ext/handle_ico/theme.php
- ext/rating/main.php
- ext/tag_edit/main.php
- Read ICO header with proper sign
- Fixes width/height being read incorrectly when >= 128
- Use Image->get_image_link() on ICO files
- Makes ICO files respect the "Nice URLs" option
- Check for existence of POST var tag_edit__owner before using it
- Fixes an error when tag_edit__owner isn't supplied, useful for automated processes where you don't want to modify the owner
- Sanitize ratings
- Before, it was possible to use a crafted POST to set a bogus rating. As a result, the post would become unviewable by anyone.
- Remove get_ico page
- It's no longer needed because ICO now uses Image->get_image_link()
- It's recommended to use ./image/$image_id instead
> Misc. Bugfixes

- ext/rating/main.php
- ext/rating/theme.php
- ext/relatationships/theme.php
- Hide the rating editor outside of edit mode
- Instead, it shows the human-friendly name of the current rating. Note that this has no effect when JS is disabled because then there's no choice but to show the editor.
- Show image rating in image info box even when not logged in
- I found it odd that the image's rating would disappear if you weren't logged in. This fixes that.
- Removed trailing period from "Parent: None." for consistency
- No other image editor properties that I know of use a trailing period
> Image info tweaks

- ext/arrowkey_navigation/main.php
Fixes an issue where the arrow key navigation extension would conflict with browser forward / back shortcuts
> Ignore arrow key navigation when modifier keys held

- ext/tag_list/theme.php
Fixes minor HTML errors where tag info links could contain illegal characters
> url_escape tag info link tag

- ext/handle_ico/theme.php
- ext/handle_pixel/script.js
- ext/handle_svg/main.php
- ext/handle_svg/theme.php
- ext/handle_video/theme.php
- Added zoom support to webm, svg, and ico
- Note that this makes webm no longer stretch to 100% width. An additional zoom mode could be added if the old behavior is desired.
- Re-apply zoom upon window resize
- This affects the "Fit Height" and "Fit Both" zoom modes. Before, the user would have to refresh the page or toggle zoom settings to get the zoom to update.
- When loading an SVG, it now uses the size of the outermost SVG element. Before, the size could be reported incorrectly when there were nested SVG elements.
- The code that handles zooming is part of the handle_pixel extension. Making it handle other formats may be considered a breach of responsibility. Perhaps the zoom functionality could be moved to its own extension.
- This expands the usage of `.shm-main-image` and …
> Enhance zoom

- ext/random_list/main.php
- ext/random_list/theme.php
This adds a search API and matching form to the random list.
A few side effects are present:
- Much of the random list's GUI has been moved into a themelet. As a result, the random list is now themeable.
- #567 is partially fixed. Instead of showing an error, it instead omits images that the user doesn't have permission to view. Mind that this isn't a complete solution given that it reduces the number of search results when it happens.
> Searchable random list

- ext/tag_list/theme.php
- themes/danbooru/style.css
- themes/danbooru2/style.css
- themes/default/style.css
- themes/futaba/style.css
- themes/lite/style.css
- themes/material/style.css
- themes/warm/style.css
This change organizes the sidebar tag lists into tables. Originally I had used lists, but then later decided that tables were a better fit (see https://github.com/shish/shimmie2/pull/581).
Additionally, this updates all of the built-in themes to keep the same general look.
Tag lists are currently structured as a bunch of loose elements punctuated with `<br/>` tags. Organizing them as a table has several advantages:
- Cleaner HTML
- Easier to style
- Sortable*
\* This feature is implemented and works, but it requires that the table headers be visible. All of the built-in themes hide the table headers.
- The spacing is slightly different now. Often, the tag list is shifted downward by a pixel or two. This also varies a little across browsers, with Edge notably increasing the line height …
> Use tables for tag lists

- core/imageboard.pack.php
- core/sys_config.inc.php
- core/user.class.php
- core/util.inc.php
- ext/ext_manager/main.php
- ext/image/main.php
- ext/index/main.php
- ext/upgrade/main.php
- ext/word_filter/main.php
This changes the PHP version check in util.inc.php to use a configuration constant, rather than the hard-coded version number in the code itself. (As it seems this hard-coded version number is easy to forget about -- and then it never gets updated.).
Also includes some more linting and PHPDoc comments.
> PHP Version check in the code should use a configurable value.

- core/imageboard.pack.php
- core/util.inc.php
- ext/index/main.php
- ext/ouroboros_api/main.php
- ext/rating/main.php
- ext/view/theme.php
- ext/wiki/main.php
- tests/bootstrap.php
- themes/lite/layout.class.php
Mostly just a little bit more linting.
Also, remove the wrapper for mb_strlen and mb_internal_encoding, as they have been in core PHP since version 4.0.6. (mb_strtolower has also been in core PHP since version 4.3.0).
> Some more linting

- .htaccess
- ext/handle_svg/main.php
- ext/handle_svg/theme.php
SVG allows inline Javascript execution when fetched as an \<object\>. Using \<img\> stops this.  
Example SVG using alert(): [example.svg](https://codeanimu.net/random/archive/uploads/example.svg)
Some related reading:
* https://bartblaze.blogspot.co.uk/2016/11/nemucod-downloader-spreading-via.html
* https://security.stackexchange.com/q/143141
* https://stackoverflow.com/questions/33387722
* https://www.w3.org/wiki/SVG_Security
> Fix SVG XSS

- core/imageboard.pack.php
Fixes "PHP Fatal error:  Uncaught TypeError: Argument 2 passed to
TagSetEvent::__construct() must be of the type array, string given"
upon bulk add.
> Fix error upon bulk add.

- core/imageboard.pack.php
- ext/bulk_add_csv/main.php
- ext/cron_uploader/main.php
- ext/handle_flash/main.php
- ext/handle_ico/main.php
- ext/handle_mp3/main.php
- ext/handle_pixel/main.php
- ext/handle_svg/main.php
- ext/handle_video/main.php
- ext/oekaki/main.php
- ext/ouroboros_api/main.php
- tests/bootstrap.php
This pull-request is somewhat related to the following issues/bug/pull-requests:
#575,  #610, #611, #612 
We should be more consistent and should ensure that `metadata['tags']` is always an array, in order to prevent issues like the previously mentioned bugs.
> Ensure that metadata['tags'] is always an array

- ext/cron_uploader/main.php
This is a follow-on to pull-request #614. One more location where `$tags` isn't converted to an array but really should be. (This fixes issue #545).
> Another location where $tags should be an array instead of a string.

- ext/handle_video/main.php
When generating video thumbnails, the exec() call to ffmpeg is currently only escaped in the case where the "ignore video scale" configuration is set to true. In the "else" branch, the raw command is executed (!).
> Add missing escaping of ffmpeg shell command during video thumbnail generation

- core/util.php
- ext/cron_uploader/main.php
Changes path-to-tag to merge path tags and filename tags.
Changes cron upload to mirror the subdir structure on output.
Changes the path-to-tag regexp to allow extensions with numbers.
Added early escape to the cron upload process when a transaction-invalidating error occurs.
> Cron upload changes

- ext/rating/main.php
I ran some tests, all the SQL works fine against pgsql. individual and bulk ratings works, and setting the different rating user levels. Resolves #649
> Enabled rating extension for pgsql

- ext/tag_list/theme.php
When you're using the `tag_categories` extension, you can get a case where the only tags that are shown are all in the category blocks and the main **Tags** block is empty, which looks weird. Seems like it's better to leave it out if that's the case, so that's what this change does \o/
> Only show 'Tags' block when there's a tag to put in it

- core/imageboard/image.php
- core/imageboard/tag.php
In SQLite, tags that contain underscores (e.g. `character:Some_Person`) can't be searched. The issue is that SQLite specifically decides to not use `\` escaping that `Tag::sqlify` applies ([this page](https://www.sqlite.org/lang_expr.html) says _"C-style escapes using the backslash character are not supported because they are not standard SQL."_).
This PR adds the appropriate `ESCAPE` clause and also makes `Tag::sqlify` escape backslashes properly, have only tested with SQLite so not sure whether the `sqlify` part of these changes would also be appropriate for MySQL/etc… have been testing this out by changing tag names in the db directly so if shimmie specifically disallows `\` from tag names then feel free to let me know and I'll rip that part out \o/
> Fix SQLite underscore searching

- themes/danbooru2/index.theme.php
- themes/danbooru2/layout.class.php
- themes/danbooru2/style.css
Just updates some stuff with the danbooru2 theme, basically:
Before, when you searched for a term, the result image links were a bit mangled. e.g. if I searched for the term 'wings', the result link would be `http://192.168.0.252:8123/index.php?q=/post/view/81search=wings`, dodgy because the image ID `81search=etc` doesn't exist (the stock theme returns `/post/view/81#search=wings` as expected). I've just made this theme do what the default theme does here and it works a lot better without any regressions or other breakages from what I can see.
Header didn't properly make the top parent link 'tab' blue, now it does so and makes the theme feel a bit nicer to use. What the header now looks like with this change applied:
> Minor danbooru2 theme fixes

- core/dbengine.php
Shimmie sends date data as 12-hours format to SQLite. I assume that's why "about 12 hours ago" error occurs when you upload images or submit a comment between 12:00:01 to 23:59:59.
> fixing "12 hours ago" error when using SQLite

- Dockerfile
The default Dockerfile doesn't build for me, it always dies on calling that init script. This just explicitly marks the init script as executable before calling it which resolves the build issue on my end.
> Fix Dockerfile script not being marked as executable

- themes/danbooru/themelet.class.php
- themes/danbooru2/themelet.class.php
The strict type changes broke the danbooru and danbooru2 themes, this PR just adds the same small change that exists in the base theme so these are fixed too. I'm not super familiar with the way themes work these days so if there's a better way to do this just let me know, thanks!
> Fix danbooru themes with new strict types

- ext/tag_categories/main.php
- ext/tag_list/main.php
When tag categories are enabled, the tag map and alphabetic list are now both coloured as expected, e.g.:
> More tag category integration

- ext/index/theme.php
- ext/wiki/main.php
- ext/wiki/theme.php
- themes/danbooru/index.theme.php
- themes/danbooru/style.css
- themes/danbooru2/index.theme.php
- themes/danbooru2/style.css
- themes/default/style.css
- themes/futaba/style.css
- themes/warm/style.css
This colours wiki titles using tag categories, and also adds 'shortwiki' entries when viewing a single tag.
On some image board software, when you're only searching for a single tag it'll show you a short blurb about that tag. How this works in Shimmie with this PR is that you enable the _"Show shortwiki entry when searching for a single tag"_ checkbox in the board settings screen, then click on a tag. If no entry exists yet it'll just show you the title with a link to setup an entry. If an entry does exist it'll show you that plus the first line of that entry (just splits on newline and grabs the first line).
Here's how it shows up on the Danbooru2 and Default themes:
> Extend Wiki integration a bit

- ext/user/main.php
This PR fixes #716, just adds a Log Out button to themes like Lite/Danbooru/Danbooru2 that don't display the user block.
> Add logout button to themes that use subnav bar

- ext/index/main.php
The new criteria falls under `order[:|=]` and uses today's date as a seed for randomized list.
Thus the list is changing it's order every day, without any human interaction, giving a more dynamic feel to the imageboard.
> Added a new search criteria "fullrandom"

- .github/workflows/test_and_publish.yml
Looks like github updated their default container, so now it contains
postgres and postgres-client by default - we just need to manually
launch the installed-but-disabled daemon
> Fix postgres testing

- ext/index/main.php
Since the term being search for is set to lowercase, that means the comparison should also be in lowercase
> Added lower to filename search

- ext/relationships/theme.php
- ext/view/theme.php
Small change. There's probably more to add and I will push those on this same PR if I find them.
I'm working on a custom theme with responsive design and I needed to be able to easily select those unidentified blocks.
> Added 2 missing block ids on post/view

- ext/tag_categories/main.php
For some reason it wasn't there, so you had to manually type (address)/tags/categories
For a while I had no idea it existed until I dug through the code, maybe that will expose users to that feature
> Added Tag Categories link from Tags page

- ext/tag_editcloud/main.php
Sort by the number of tags (sum) for each category descending
This will allow the most used categories to appear first and not by alphabetical order
> Edit sort by Categories

- ext/ext_manager/theme.php
> Added missing colon to version title on extension page

- core/util.php
this allows passing the X-Forwarded-Proto header to Shimmie from a reverse proxy. useful when SSL/TLS is terminated at the reverse proxy
> Add support for X-Forwarded-Proto Header

- ext/wiki/main.php
- ext/wiki/theme.php
I noticed search engines indexing wiki pages on my booru that didn't exist since they return a 200 code. this option sends a 404 instead if the wiki page doesn't exist when it's enabled.
if adding the function to the WikiPage class isn't the preferred way to do this let me know how you'd prefer me to implement it
> Add option to return 404 code for nonexistent wiki pages

- Dockerfile
I was facing some errors when running Shimmie2 in a Docker container:
Which was fixed by replacing the `debian:testing-slim` source image with `debian:stable` in the Dockerfile, as suggested by @shish [here](https://github.com/shish/shimmie2/issues/849#issuecomment-964527949) (for a different issue lol).
> Fix apt errors when running in Docker

- ext/autocomplete/script.js
- ext/favorites/main.php
This allows sorting by the number of favorites a post has in the same way as other ordering metatags. If there's a better way to handle conditionally showing the metatag in autocomplete, let me know!
closes friends-of-the-core/shimmie2#1
> Allow ordering by favourites in searches

- ext/media/main.php
ffmpeg's `thumbnail` filter by default [loads one hundred frames into memory](https://ffmpeg.org/ffmpeg-filters.html#thumbnail) to determine the most representative.
For 4K videos this can mean ffmpeg memory usage in excess of a gigabyte, as the analysis is performed on frames of the input video's frame size. I'm running Shimmie on a bit of a potato machine where this is too much! 😅 As a result, the entire PHP process is out of memory killed, and the thumbnail goes ungenerated.
It turns out, however, that you can ask ffmpeg to scale the video before it thumbnails it, significantly reducing the memory requirements. This makes Shimmie work in my specific case, but is also a decent efficiency improvement for others! ☺️
closes friends-of-the-core#5
> Scale thumbnails in ffmpeg to avoid excessive memory use on high-resolution videos

- core/imageboard/image.php
- ext/rotate/main.php
**Note**: This change relies on #875, and includes that commit until it is merged.
The image rotation extension currently relies on creating a new Image instance, and this doesn't change that, but it does make it keep the original upload date rather than replacing it.
closes friends-of-the-core#4
> Preserve posted date on rotate

- core/captcha.php
- core/imageboard/image.php
- core/sys_config.php
- core/util.php
- ext/comment/main.php
- ext/image_view_counter/main.php
- ext/ipban/main.php
- ext/log_db/main.php
- ext/log_logstash/main.php
- ext/log_net/main.php
- ext/notes/main.php
- ext/pm/main.php
- ext/pm_triggers/main.php
- ext/source_history/main.php
- ext/tag_history/main.php
- ext/user/main.php
- ext/varnish/main.php
- ext/wiki/main.php
- index.php
- tests/defines.php
Related to #800 and #862 
I added 2 features to make it easier to run Shimmie2 behind a reverse proxy.
1. Setting the global `REVERSE_PROXY_X_HEADERS` to true will get IPs from the `X-Real-IP` header and the protocol from `X-Forwarded-Proto`. I didn't use `X-Forwarded-For` because some proxy servers set it to a list of IPs which is somewhat ambiguous.
2. Config options to set the host that should receive Varnish PURGE requests
> X-Real-IP support and Varnish PURGE config options

- ext/autocomplete/script.js
- ext/tag_edit/theme.php
This updates the autocomplete and tag_edit functionality to allow autocompletion in both the individual image tag editor, and in the sidebar bulk operations editor.
It pulls from the same source as the existing search autocomplete, albeit without metatags and negative matches.
> Autocomplete in more places

- core/userclass.php
Shimmie out of the box has bulk downloads enabled for the 'user' and 'base', but perform bulk actions isn't enabled, so it goes to a handler not found page. This fixes that.
> fix no handler for 'bulk_download'

- ext/approval/main.php
- ext/comment/main.php
this allows a user to view the images they've uploaded, even if they haven't been approved. helpful to allow use of quality-of-life features like the tag edit cloud or correction of mistakes before approval
the owner may also comment on the unapproved image but these comments are hidden from the comment list until the image is approved
> Allow image owner to view their unapproved images

- core/cacheengine.php
Add an additional OR conditional for memcache usage. If you use the DSN as listed at https://github.com/shish/shimmie2/wiki/Performance#software-cache the memcache section will never run because it is looking only for DSNs with 'memcached' causing an exception to be thrown on the first access as the cache is never setup.
> Update memcache DSN condition matching

- core/install.php
Hello! I'm new to Shimmie and today I tried running the latest version. Looks like some string conversions are missing from the install.php. Thank you!
> Fix database not detected on installation

- ext/transcode/main.php
- ext/upload/config.php
- ext/upload/main.php
This is an idea to solve https://github.com/shish/shimmie2/issues/848
I think it's a step towards "full control of filetypes" on `upload`, as well as on `transcode`.
Idea is to allow for _all_ uploads / or a subset, but if  the maintainer wants, they can force them all to convert to a single format (or many). Currently there's already the ability to set an "transcoding mapping table" from input -> output, as well as enabling the transcoding on upload. This might help on guarding against weird file formats that might not work well with transcoding, or if you don't want to deal with them (on your instance).
Reason for having the "upload" check in the `ext/transcode/main.php` file is because it seems that `onUploadData` in the transcode happens _before_ the one in the `ext/upload/main.php` …
> implement MIME checks on upload

- core/permissions.php
- core/userclass.php
- ext/approval/main.php
- ext/approval/theme.php
Hi! I implemented this quick change for images to be auto-approved on upload if the user has a special new permission to bypass the aproval process. A few things to note:
1. Possible improvement: I found it weird that I had to use the `approve_image` method instead of `$event->image->approved = true`, as this wasn't working. Is it because the `approved` boolean is not part of the default Image class?
2. I could've reused the existing permission for the bypass. After all, if you can approve posts you can approve your own. But doing it this way lets you assign only the bypass permission to a userclass, trusting all their posts by default but not letting them approve others'.
3. To keep the existing behaviour, I made a configuration option so that bypass is disabled by default. It can of …
> Approval bypass

- ext/blocks/main.php
- ext/blocks/theme.php
Addressing #624, new documentation/help for the blocks extension might be needed.
Basically:
The userclass parameter can be left empty for blocks to show to everyone, or specified as a comma-separated, case-insensitive list of user classes that will see that block. Spaces around the comma get stripped.
Example, I have 3 blocks with the following content and userclass values:
- "You are not logged in": `anonymous`
- "You are logged in": `user, admin`
- "You are an admin": `admin`
A real use case:
- "<**ad here**>": `user, anonymous`
- "Thanks for supporting us!": `supporter`
> show blocks based on user class

- core/basethemelet.php
- core/user.php
- core/util.php
- ext/pools/main.php
- ext/pools/theme.php
- ext/rating/main.php
- ext/rating/theme.php
Same proof of concept from #827 but without my custom wrapper. `build_selector` has been moved to `basethemelet.php`. I didn't even think of it before. Putting this function here means that in addition to overriding on the entire site, themes can override them on a per-extension basis, giving even more control to the designer.
Let's just hope we don't override the new functions on extensions themselves or we will end up in the same road :smile:
- The doc-string might be a bit too much, I just wanted to make it clear for this PR.
- There's an unrelated change that makes pools sort posts by ID when order is the same. It was a personal uncommitted change and it slipped on this one.
If this looks good, I will implement `build_selector` on more extensions.
> Standard HTML select code

- core/imageboard/misc.php
- core/tests/urls.test.php
- core/urls.php
- ext/approval/main.php
- ext/artists/theme.php
- ext/browser_search/main.php
- ext/favorites/main.php
- ext/home/theme.php
- ext/image/main.php
- ext/index/main.php
- ext/index/theme.php
- ext/notes/theme.php
- ext/numeric_score/main.php
- ext/rating/theme.php
- ext/relationships/theme.php
- ext/tag_edit/main.php
- ext/tag_edit/theme.php
- ext/tag_history/theme.php
- ext/tag_list/theme.php
- ext/trash/main.php
- ext/upload/test.php
- ext/upload/theme.php
- ext/user/main.php
- themes/danbooru/comment.theme.php
- themes/danbooru2/comment.theme.php
escaping things properly is hard D:
> dedicated search_link() function

- .htaccess
When using recent versions of Apache and the provided `.htaccess` file (with "Nice URLs" enabled in Shimmie), you get 403 Forbidden when attempting to navigate to a URL containing spaces, e.g. `http://<shimmie>/post/list/tag1%20tag2/1`.
Apache's error log shows:
```
AH10411: Rewritten query string contains control characters or spaces
```
We fix this by adding `B` and `BNP`, as per [here](https://webmasters.stackexchange.com/a/141978).
> Fix .htaccess rewrite

- ext/pools/main.php
- ext/pools/theme.php
- ext/relationships/theme.php
- themes/danbooru2/view.theme.php
> Pool search

- core/microhtml.php
- ext/artists/theme.php
- ext/image_view_counter/main.php
- ext/post_titles/theme.php
- ext/rating/theme.php
- ext/relationships/theme.php
- ext/rule34/main.php
- ext/tag_edit/theme.php
- ext/view/main.php
- themes/rule34v2/tag_edit.theme.php
Rather than having a boolean for view or edit + optional editor, use the existence of the editor to know if a field is editable
> Make SHM_POST_INFO more logical

- core/imageboard/search.php
```
QUERY PLAN
------------------------------------------------------------------------------------------------------------------------------------------------------------
Aggregate  (cost=657728.66..657728.67 rows=1 width=8) (actual time=4842.412..4842.414 rows=1 loops=1)
->  Index Scan Backward using images_pkey on images  (cost=0.43..631953.33 rows=2062026 width=2377) (actual time=148.217..4729.022 rows=2039895 loops=1)
Filter: (numeric_score > 2)
Rows Removed by Filter: 3452140
Planning Time: 0.208 ms
JIT:
Functions: 6
Options: Inlining true, Optimization true, Expressions true, Deforming true
Timing: Generation 0.848 ms, Inlining 8.995 ms, Optimization 74.704 ms, Emission 64.108 ms, Total 148.655 ms
Execution Time: 4843.408 ms
```
```
QUERY PLAN …
```
> [core] don't specify ORDER BY when counting total number of results, which allows the DB to be much faster

- core/database.php
- ext/index/main.php
Currently order:random_XXXX is broken on SQlite (and AFAIK PostgreSQL too) due to RAND() being called with a seed, which is not supported.
This pull requests adds a new call to the Database which generates SQL code that, depending on the engine, will keep using the fast seeded RAND(N) if supported, or fall back to using a DRBG based on MD5.
It has been added to Database instead of the Main extension so it can be reused elsewhere if needed.
> Fix order:random not working on SQlite

- core/polyfills.php
- ext/et/main.php
`disk_total_space` and `disk_free_space` return floats already, so we can avoid triggering an integer overflow by just working using those floats instead.
> Do not cast hard drive size to integer - fixes #1037

- ext/rating/main.php
- ext/rating/theme.php
- ext/upload/events/upload_rating_building_event.php
- ext/upload/main.php
- ext/upload/theme.php
If the Post Ratings extension is enabled, encourage a rating to be selected when uploading.
This can be extended to also have a Common Ratings field, if wanted.
> [upload] add rating fields to upload form

- ext/comment/theme.php
- themes/danbooru/comment.theme.php
- themes/danbooru2/comment.theme.php
- themes/futaba/comment.theme.php
This prevents a very short comment from having the ellipsis (...) appended to it.
This commit also makes trimming consistent across themes (default theme truncated without any ellipsis to signal truncation, danboorus and futaba had ellipsis).
> Fix unnecessary truncation when trimming comments

- ext/notes/style.css
If the notes extension is enabled, the container would block clicking the image, including right-clicking to save it
> [notes] allow clicking through notes container

- ext/index/theme.php
These help to show off the power of wildcard searches with practical examples, as well as demonstrating that it can allow a tag with no extra characters.
> add wildcard search examples

- core/extension.php
- core/imageboard/event.php
- core/imageboard/misc.php
- core/testcase.php
- core/util.php
- ext/artists/main.php
- ext/bulk_add_csv/main.php
- ext/bulk_import_export/main.php
- ext/cron_uploader/main.php
- ext/danbooru_api/main.php
- ext/favorites/main.php
- ext/graphql/main.php
- ext/handle_archive/main.php
- ext/ouroboros_api/main.php
- ext/post_lock/main.php
- ext/post_lock/test.php
- ext/post_owner/main.php
- ext/post_owner/test.php
- ext/post_source/main.php
- ext/post_source/test.php
- ext/post_tags/main.php
- ext/post_titles/main.php
- ext/rating/main.php
- ext/upload/main.php
- ext/view/events/image_info_set_event.php
- ext/view/main.php
[core] Deduplicate ImageAdditionEvent & ImageInfoSetEvent
Rather than ImageAddition triggering TagsSet/SourceSet/LockSet etc in one way, and ImageInfoSet triggering TagsSet/SourceSet/LockSet in a different way, why not have ImageAddition *just* deal with image addition, and then send a separate ImageInfoSet to deal with all of the metadata setting?
> [core] Deduplicate ImageAdditionEvent & ImageInfoSetEvent

- core/permissions.php
- core/userclass.php
- ext/forum/main.php
- ext/notes/main.php
- ext/notes/script.js
- ext/notes/theme.php
[core] fix permissions in forum and notes
This includes preventing silent failures when permission is denied, preventing unauthorized users from being shown the note edit form, patching typos, and extracting NOTES_REQUEST to its own permission
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/shimmie2/pull/1057).
* __->__ #1057
* #1056
> [core] fix permissions in forum and notes

- core/userclass.php
Up until now I've been mentally defining an "admin" as "Somebody who has access to *all* current *and future* features" (as opposed to "Somebody who has access to a large but finite number of features") - having the code line up with this mental model seems less misleading (and leaves less room for future bugs)
`Permissions::HELLBANNED` is a special snowflake - that's more like "an attribute of a user"  than "a permission", and IMO using the permission system for that was a mistake; it just happened to be the quickest way to get results at the time...
> [core] give admin all permissions

- core/util.php
[core] don't crash if TRUSTED_PROXIES isn't defined, fixes #1061
> [core] don't crash if TRUSTED_PROXIES isn't defined, fixes #1061

- core/util.php
[core] don't crash when REMOTE_ADDR is 'unix:', fixes #1076
> [core] don't crash when REMOTE_ADDR is 'unix:', fixes #1076

- core/imageboard/tag.php
- ext/post_tags/main.php
- ext/post_tags/test.php
[core] don't limit searchable tag length, only writable length, fixes #1087
> [core] don't limit searchable tag length, only writable length, fixes #1087

- ext/graphql/main.php
- ext/graphql/test.php
[graphql] take post metadata as arbitrary key-value pairs
I don't want "tags" and "source" to be special things where we explicitly handle those and fail to handle anything else. Making all metadata fields {string:string} pairs seems nicer, and matches with HTTP POST syntax
> [graphql] take post metadata as arbitrary key-value pairs

- .docker/run.php
[docker] use ini_parse_quantity for post_max_size, see #1096
> [docker] use ini_parse_quantity for post_max_size, see #1096

- core/event.php
[core] differentiate permission denied due to missing permission vs error, see #1103
> [core] differentiate permission denied due to missing permission vs error, see #1103

- ext/tag_list/main.php
[tag_list] only match 'GET /tags/{sub}', to avoid conflicting with 'POST /tags/categories'
> [tag_list] only match 'GET /tags/{sub}', to avoid conflicting with 'POST /tags/categories'

- ext/tag_categories/style.css
- ext/tag_categories/theme.php
Pulling this from a custom theme I have used for a while. adds a color swatch next to the hex code to show the current color of each category. also changes the category editor to use a color input instead of a text input to match the new category creation form
I noticed the preview for the color input was too short to be visible so added an explicit height
color input before:
color input after:
> Minor improvements to tag category editor

- ext/post_source/main.php
- ext/post_source/theme.php
- ext/post_tags/main.php
- ext/post_tags/theme.php
- ext/rating/main.php
- ext/rating/theme.php
- ext/upload/events/upload_common_building_event.php
- ext/upload/events/upload_header_building_event.php
- ext/upload/events/upload_specific_building_event.php
- ext/upload/theme.php
Builds upon #1052
First commit creates events for adding fields to the upload form, and replaces the hardcoded 'tags' and 'source' fields.
Second commit adds the ratings field to the upload form.
> Build upload post fields using events, add ratings field to upload page

- ext/filter/style.css
Unsetting the display option can disable `display: block`, which allows the thumbnails to be centred in their container
> [filter] fix thumb display css

- ext/user/main.php
- ext/user/test.php
In `user_admin/create_other`, would just send pass1 twice.
> [user] fix typo in password check

- core/testcase.php
- ext/terms/info.php
- ext/terms/main.php
- ext/terms/theme.php
This extension replaces pages with a terms and conditions message until they accept it (or login). The message can be customised e.g. to include an 18+ age limit.
It also adds the cookie to test requests to prevent them getting this page.
> [terms] add terms and conditions gate

- ext/handle_pixel/script.js
If an image will change size when clicking, this will show a zoom-in or zoom-out cursor when the mouse is over it. This helps tell the user that the image can be enlarged.
> [handle_pixel] show zoom cursor on images

- themes/danbooru2/view.theme.php
Fixes #1151
Danbooru2 theme overrides the search field on the view page, failing to include the autocomplete class.
> [danbooru2] add autocomplete to view search field, fixes #1151

- core/util.php
This allows a contact link to be something like "/wiki/contact".
This is better than an absolute links ("https://booru.example.org/wiki/contact"):
- the booru ever changes domain name (or has multiple domain names)
- the booru uses multiple protocols (e.g. has a regular domain and also a Tor .onion address)
> [core] Allow relative links for contact link

- core/basethemelet.php
- ext/ratings_blur/info.php
- ext/ratings_blur/main.php
- ext/ratings_blur/style.css
- ext/ratings_blur/test.php
This allows thumbs with certain ratings to be blurred until hovered over (or long-tapped on a touchscreen). This is made for boorus where explicit content should be available, but blurred out by default.
The admin can set the global default level to blur (e.g. Explicit, Questionable & Explicit, none) and user accounts can override it in their settings. Anon users receive the global default.
The second test function (`testRatingBlurGlobalConfig`) creates and deletes a test account. This is to simulate an anon user loading the global config. If there is a better way to do this, I can try and improve it.
> [blur] blur thumbs with explicit rating

- core/user.php
Every database has its own unique way of hashing data (md5 is _mostly_ consistent, but stronger hashes vary a lot more) - doing it on the PHP side means we only need to write the code once
> [core] have User::by_session() check session ID on the PHP side

- core/microhtml.php
- core/util.php
- ext/bbcode/info.php
- ext/bbcode/main.php
- ext/bbcode/style.css
- ext/bbcode/test.php
- ext/bulk_add_csv/info.php
- ext/comment/theme.php
- ext/cron_uploader/theme.php
- ext/et_server/main.php
- ext/favorites/theme.php
- ext/help_pages/style.css
- ext/media/theme.php
- ext/mime/theme.php
- ext/notes/theme.php
- ext/numeric_score/theme.php
- ext/private_image/theme.php
- ext/relationships/theme.php
- ext/tag_categories/theme.php
- ext/trash/theme.php
- themes/danbooru/style.css
- themes/danbooru2/style.css
- themes/default/style.css
- themes/futaba/style.css
[`<code>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/code) is a tag used for code, including filepaths and other text a computer would recognize. `<pre>` is used to preserve the whitespace, useful for multi-line code (among other things like ASCII art). While code can simply be put in a `<pre>` tag, it seems to be recommended to use a `<code>` tag, with a `<pre>` tag around it when declaring a multi-line code block.
Many extensions already use `<code>` in documentation, this commit standardizes it for consistency.
This commit also moves the theming for code out of the bbcode extension and into themes. This allows it to be used in other places `<code>` is used, like in extensions documentation. It also allows themes to customize code CSS (such as the default theme, which …
> use <code> where appropriate

- ext/comment/theme.php
Lowers the priority of tall "Comments" box on the `post/list` pages, so the more critical fields "Popular Tags" and "Refine Search" are clearly visible to the user.
> [comment] move recent comments below tags on post list

- themes/danbooru/view.theme.php
- themes/danbooru2/view.theme.php
- themes/lite/view.theme.php
Danbooru* and Lite themes add an image metadata section listing the rating. This is updated to have a search link, like the rating listing on the post metadata.
This also removes a redundant condition.
> [themes] add search link to rating

- ext/alias_editor/theme.php
This commit adds a small message telling users about tag aliases and tag implications. It also gives a hint for how to make a tag implication (which I did not know as a feature of Shimmie until I found https://github.com/shish/shimmie2/issues/320 \o/ )
> [alias] add info on tag aliases and tag implications

- core/basepage.php
- core/basethemelet.php
- ext/browser_search/main.php
- ext/custom_html_headers/main.php
- ext/downtime/theme.php
- ext/emoticons_list/theme.php
- ext/filter/main.php
- ext/filter/theme.php
- ext/google_analytics/main.php
- ext/handle_mp3/theme.php
- ext/holiday/main.php
- ext/home/theme.php
- ext/image/main.php
- ext/index/theme.php
- ext/notes/theme.php
- ext/regen_thumb/theme.php
- ext/rss_comments/main.php
- ext/rss_images/main.php
- ext/site_description/main.php
- ext/site_description/test.php
- ext/terms/theme.php
- ext/user/main.php
- ext/view/theme.php
I wanted to ensure that all pages (even the downtime page, terms page, home page, etc) had the appropriate `data-` attributes on `<body>` (because those are required for certain javascript, eg autocomplete, to work). One thing led to another and now everything in `head` is microhtml'ed
> microhtml for everything in <head>

- ext/statistics/main.php
- ext/statistics/theme.php
Commit 1 corrects a major inaccuracy by sorting the data in correct order.
Commit 2 aliases tags before counting changes. This is a bit of a trade-off, it does eliminate changes made before an alias was added, but it does prevent alias changes from counting towards whoever edited the tags next. It also includes the total number of edits made.
Commit 3 makes the names on the stat lists into links for easy of use.
> [statistics] various fixes

- ext/numeric_score/main.php
While testing my QueryBuilder with various extensions, numeric score wouldn't work with the sqlite database, so I added statements so it works.
> Added sqlite compatible date criteria to numeric score, plus some fixes

- Dockerfile
[docker] remove unused tests target
> [docker] remove unused tests target

- core/cli_app.php
- core/imageboard/image.php
- core/polyfills.php
- core/testcase.php
- core/user.php
- core/userclass.php
- core/util.php
- ext/alias_editor/main.php
- ext/auto_tagger/main.php
- ext/danbooru_api/main.php
- ext/numeric_score/main.php
- ext/numeric_score/test.php
- ext/post_owner/main.php
- ext/replace_file/main.php
- ext/setup/main.php
- ext/source_history/main.php
- ext/tag_history/main.php
- ext/user/main.php
- ext/user/test.php
- ext/user_config/main.php
[core] Make User::by_name / User::by_id not-null
Nearly everywhere that these functions are called, the result is assumed to be not-null, and a null will break things
> [core] Make User::by_name / User::by_id not-null

- ext/setup/main.php
Fixes issue where a checkbox cannot be set as false if the default value is true (for example, the "Allow new signups" setting could not be disabled).
> [setup] allow setting bool option to false if default is true

- ext/filter/main.php
This code is not functional or necessary and gives an error because the code wasn't raw HTML. It can be safely removed.
> [filter] remove broken code

- ext/relationships/theme.php
This fixes the cases where a registered user is not allowed to set parents, or where an anonymous user is allowed to set parents.
> [relationships] use permission to check if editable

- core/user.php
[core] use salted sha3 instead of md5 for session tokens
> [core] use salted sha3 instead of md5 for session tokens

- core/imageboard/search.php
- core/permissions.php
- core/send_event.php
- core/sys_config.php
- core/urls.php
- ext/comment/main.php
- ext/index/main.php
- ext/rss_images/main.php
- ext/speed_hax/info.php
- ext/speed_hax/main.php
- ext/tag_list/main.php
- ext/user/main.php
- index.php
- tests/defines.php
- tests/phpstan.neon
This allows an admin to choose which speed tweaks to enable.
Pulling this code will require a change to documentation: https://github.com/shish/shimmie2/wiki/Performance#software-tweaks
I also couldn't find what code this point was referring to: "- HTML for thumbnails is cached"
> [speed_hax] extract SPEED_HAX tweaks to extension

- ext/tag_history/main.php
- ext/tag_history/style.css
- ext/tag_history/theme.php
This makes it much easier to see when a tag was introduced in each entry.
Using `explode` instead of `Tag::explode` prevents tags being aliased in the tag history, which could make some entries identical (consider the example, where the aliases `stirner`->`max_stirner` and `anarchist`->`anarchism` were introduced. If `Tag::explode` were used, it would not show any change as the tags in the old entry would be aliased to be the same as the newer ones).
This also prevents the database being queried on each tag, massively improving performance on tag history pages.
> [tag_history] show colour-coded tag changes, remove tag aliasing

- ext/view/theme.php
This adds extra `twitter:` and `og:` meta tags for posts (most importantly, `<meta property="twitter:card" content="summary_large_image">`), and changes the thumbnail link to the image link, in order to display full-sized images in embeds. For example, this is what a post looks like on Discord:
> Generate summary_large_image preview for images

- ext/pm/main.php
Message cache was not updating when reading a pm, found the issue to be a mistyped cache key
> Fix a typo in a cache key

- composer.json
- composer.lock
- core/tests/UtilTest.php
- core/util.php
Replace flexihash with weighted rendezvous hashing
`Flexihash.php` hasn't been maintained for years and isn't php8.4 compatible; WRH is much simpler, and much better balanced, and nearly as fast
> Replace flexihash with weighted rendezvous hashing

- .github/get-tags.py
- .github/workflows/tests.yml
This modifies the Github Workflow steps by using Docker's official images for building to multiple architectures. I tried to keep parity with the current format, but I also added some new (optional) parameters for envvars that allow the user to choose a different image name and registry.
In order to test this, I created [a non-fork repo](https://github.com/BadMannersXYZ/shimmie2-test) (by default, Github doesn't allow forks to share secrets to workflows). This has [built an image](https://hub.docker.com/layers/badmanners/shimmie2/latest/images/sha256-066fcf3a1cd455e53d926ecc8c2a07ea00ad24f4bf370b0401ec3a46432a6de4?context=repo) that I've tested on my Raspberry Pi, and it seems to work perfectly, although I haven't tested the corresponding amd64 image yet.
> [docker] Build image for amd64 and arm64

- ext/notes/main.php
- ext/notes/theme.php
- ext/source_history/main.php
- ext/tag_history/main.php
First commit adds the notes pages to the navbars. These were inaccessible before.
Second commit orders SQL requests by id instead of date, since date is not necessarily unique (especially if imported data from another booru software).
> Improvements to notes, tag histories, source histories

- ext/tag_editcloud/main.php
only enable tag-edit-cloud category support with mysql, fixes #1265
> only enable tag-edit-cloud category support with mysql, fixes #1265

- core/page.php
- ext/ext_manager/theme.php
- ext/home/main.php
- ext/home/theme.php
- themes/danbooru/page.class.php
- themes/danbooru2/page.class.php
- themes/default/style.css
- themes/futaba/page.class.php
- themes/lite/page.class.php
- themes/warm/page.class.php
[themes] only apply grid layout to pages generated using the default Page::body_html, fixes #1272
> [themes] only apply grid layout to pages generated using the default Page::body_html, fixes #1272

- ext/handle_pixel/script.js
- ext/handle_pixel/theme.php
Uses <img> attributes instead of CSS, improving accuracy and reducing layout shift.
> [handle_pixel] improve zooming

- core/imageboard/search.php
- ext/index/main.php
[core] simplify counting search results
`SELECT images.*` vs `SELECT COUNT(*)`
> [core] simplify counting search results

- ext/ban_words/info.php
The current title for this extension is "Comment Word Ban", however it also bans words in the tags and source.
For example, if one tries to ban links in the comments, they might unknowingly also ban links as a valid source.
> [word_ban] clarify this extension bans on source and tags

- ext/approval/main.php
- ext/artists/main.php
- ext/comment/main.php
- ext/favorites/main.php
- ext/index/events.php
- ext/index/main.php
- ext/media/main.php
- ext/mime/main.php
- ext/notes/main.php
- ext/numeric_score/main.php
- ext/pools/main.php
- ext/post_source/main.php
- ext/post_tags/main.php
- ext/private_image/main.php
- ext/rating/main.php
- ext/relationships/main.php
- ext/tag_categories/main.php
- ext/trash/main.php
- ext/user/main.php
SearchTermParseEvent::matches(), because preg_match is a footgun
> SearchTermParseEvent::matches(), because preg_match is a footgun

- core/polyfills.php
I was running 2.10.6 and noticed after updating to latest version that the booru was running way, way slower. I tracked it down to the truncate function, which was struggling with the thousands of words in the recent comments.
This PR severely improves the performance:
```
$ time curl http://192.168.0.245/booru/index.php?q=post/list -o/dev/null
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  103k    0  103k    0     0  20205      0 --:--:--  0:00:05 --:--:-- 26273
real    0m5.258s
user    0m0.000s
sys     0m0.031s
```
```
$ time curl http://192.168.0.245/booru/index.php?q=post/list -o/dev/null
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left …
```
> Improve text truncation speed

- core/extension.php
- core/tests/InitTest.php
- core/tests/PageTest.php
- core/tests/UtilTest.php
- ext/admin/test.php
- ext/comment/theme.php
- ext/favorites/main.php
- ext/graphql/test.php
- ext/help_pages/test.php
- ext/image/main.php
- ext/image/test.php
- ext/index/test.php
- ext/media/main.php
- ext/pools/test.php
- ext/res_limit/test.php
- ext/user/test.php
- ext/user_config/main.php
in preparation for phpstan 2.0
> Remove redundant asserts

- ext/favorites/main.php
- ext/index/theme.php
The id of the user was determining the post number that was being updated rather than the post's id. This only affected the `favorites>n` search query which is why it went unnoticed for 13 years.
sql statements for those interested
correct posts that may not have any favorites but whose favorite count was incorrectly updated
`UPDATE images SET favorites=(SELECT COUNT(*) FROM user_favorites WHERE image_id=id) WHERE favorites>0;`
set the correct favorite count for all favorited posts
`UPDATE images SET favorites=(SELECT COUNT(*) FROM user_favorites WHERE image_id=id) WHERE id IN (SELECT image_id FROM user_favorites);`
> Fix Favorites Bug

- Dockerfile
php 8.2 is having support dropped soon, and debian has decided to stick with 8.2 for the next 5 years x_x
> php 8.3 in docker

- ext/index/main.php
This patch allows specifying larger random seeds. Current value only allows for 10k possible variations, which is quite short considering these boards may contain millions of pictures.
The new value allows for 10^8 variations, so I am more likely to get a truly random image using the Danbooru/Ouroboros API with large data sets.
In order to keep autogenerated seeds short, the JS code that inserts the value will still produce only 4-digit sequences.
This should not cause any compatibility issues as [MySQL uses a 32-bit field for the seed](https://github.com/mysql/mysql-server/blob/61a3a1d8ef15512396b4c2af46e922a19bf2b174/sql/item_func.cc#L3674-L3682), which allows for log10(2**32) = ~9.6 digit seeds. The other engines fall back to the hash DRBG which accept arbitrary lengths.
> Allow larger random seeds

- core/stdlib_ex.php
- ext/ouroboros_api/main.php
8c22cb1fb65c91adcb7f16c8cd59002693e17d83 broke the Ouroboros API. These two commits fix it.
The first one prevents a deprecation warning to be thrown, as $options should be zero when not used, not null.
The second one fixes it by avoiding the page_matches call entirely. Now it will also not set the page type unless something actually matches, so unimplemented methods just use Shimmie's default "no handler found" page instead of a blank empty page.
> Fix ouroboros

- core/user.php
- ext/comment/theme.php
- ext/user/main.php
Wasn't a fan of 'gravatar', an external way to give users avatars, knowing e621 has the ability to set a post as your avatar, i wanted the same, and others might like it too so hence a pr.
since it uses user_config, it has to get the user config every time for the owner of every comment, using user_config::get_for_user($id) seemed slow as it sends a quite large event every time, so it directly gets the config in User::get_avatar_post_link(), but i am not entirely sure if its safe to do it in this way. The url or full html might also be cacheable to increase efficiency a bit thinking about it now.
> post id avatars

- ext/statistics/main.php
This function was added by mistake. It only adds a useless text box and section to the admin panel.
> [statistics] remove unused stub option

- core/config.php
- core/tests/ConfigTest.php
if an invalid value is set, we should return the default, not 0
> [core] Config unit tests, and fixes for get_int/float

- core/polyfills.php
- core/user.php
- ext/user/config.php
- ext/user/main.php
- ext/user/script.js
- ext/user/style.css
- ext/user/theme.php
- Add a button in post controls to set the image as avatar.
- Add a page to set the avatar cropping easily.
This page should make it easy for the user to crop their avatar to their liking, they can drag it around and zoom in using the slider. And if they do not have JavaScript enabled, it can be manually changed on the user options page.
All the cropping is done by CSS and does not require any changes to be made to the actual images, nor copying and resizing.
I also included the parse_shorthand_int change i mentioned in https://github.com/shish/shimmie2/issues/1390 because it does rely on that right now. A workaround would be to parse some values as string instead, then cast it to integer afterwards manually but i don't see issue in having parse_shorthand_int be able to parse negative …
> [user] Post avatars with cropping

- ext/log_console/main.php
Just some little improvements to the logger format resulting in:
The log levels are checked against the defined `SCORE_LOG_*` values, where a priority is considered in a specific log level when it is at or above the `SCORE_LOG_*` value, with the highest taking precedence over the lower values.
> [log_console] improve format

- core/testcase.php
- ext/approval/test.php
- ext/comment/test.php
- ext/downtime/test.php
- ext/rating/test.php
- ext/ratings_blur/test.php
- ext/res_limit/test.php
Humans gonna human, and the human error of leaving a `$config` setting with a weird value at the end of a unit test is a nightmare to debug - let's make sure to clean them up every time
> do a global config rollback at the end of every test

- core/user.php
- ext/avatar_post/main.php
- ext/avatar_post/theme.php
- ext/biography/main.php
- ext/cron_uploader/main.php
- ext/cron_uploader/theme.php
- ext/filter/theme.php
- ext/private_image/main.php
- ext/rating/main.php
- ext/rating/test.php
- ext/ratings_blur/main.php
- ext/ratings_blur/test.php
- ext/user/main.php
- ext/user_config/main.php
Global variables are a pain, doubly so when you have two global variables which need to be kept in sync or things will go very very badly (`$user` and `$user_config`). Having a global `$user` feels like an acceptable tradeoff, but `$user_config` is redundant.
> s/global $user_config/$user->get_config()/

- core/user.php
- ext/comment/main.php
Switches from one-query-per-comment to one-query-per-user
> [comment] Cache users in comment lists, fixes #1426

- core/tests/ShimmiePHPUnitTestCase.php
- tests/bootstrap.php
There was a lot of magic to ensure that this file didn't crash when loaded as part of `core/*.php`... but we could just _not_ load it as part of `core/*.php`
> Move base test case to core/tests/ rather than core/

- core/cli_app.php
- core/logging.php
- ext/cron_uploader/main.php
- ext/log_console/main.php
- ext/log_db/main.php
- tests/phpstan.neon
Avoiding a random handful of disconnected constants in the global namespace
> Use an enum for log levels

- ext/setup/script.js
Moves the `checkbox !== null` check above statements using `checkbox`.
> [setup] avoid console errors on other pages

- ext/user/main.php
Broken in commit a833f5fa5c7d390fef28968196e4a8ef435da15e
Where the setting before relied on `0` being interpreted as false in php, now the value is a string, and thus will always evaluate as true unless empty string which is not possible with the default given, nor the options given in `user/config.php`.
before:
`if ($config->get_int("user_loginshowprofile", 0))`
> [user] fix the redirect setting to work properly again

- core/tests/UrlsTest.php
- core/urls.php
- ext/et/main.php
- ext/reverse_search_links/theme.php
This should stop `make_link(make_link("foo"))` from slipping through
> [core] stricter validation for make_link

- ext/approval/main.php
- ext/trash/main.php
Using a leading slash in the navlinks causes the post list to fail to load with the following error:
```php
Internal Error
Message: make_link(/post/list/in%3Atrash/1): page cannot start with a slash
Version: 2.12.0-alpha (on 8.4.4)
Stack Trace:
#0 /app/core/urls.php(20): Shimmie2\make_link()
#1 /app/themes/danbooru2/page.class.php(142): Shimmie2\Link->make_link()
#2 /app/themes/danbooru2/page.class.php(108): Shimmie2\Danbooru2Page->navlinks()
#3 /app/core/page.php(565): Shimmie2\Danbooru2Page->body_html()
#4 /app/core/page.php(289): Shimmie2\Page->render()
#5 /app/index.php(106): Shimmie2\Page->display()
#6 /app/index.php(153): Shimmie2\main()
#7 {main}
```
Only affected extensions seems to be trash and approval.
> Fix navlink bug in extensions

- core/User/UserClass.php
- ext/perm_manager/theme.php
- ext/user/main.php
This means that if we have a default "user" class, and later on we add a customised "user" class, any other classes who inherit from "user" will inherit from the custom one
> [perm manager] defer getting UserClass parent

- ext/user/main.php
- ext/wiki/main.php
Both subnavs on wiki and the account page were missing, adding them back with the `$matches`  parameter
> [various] Re-add the missing subnavs

- core/Util/Url.php
(means that the Url class can work in the Installer environment)
> [core] don't even check for niceurls if we don't need them 

- core/Extension/Extension.php
- core/ImageBoard/Image.php
- core/Page/CommonElementsTheme.php
- core/Testing/ShimmiePHPUnitTestCase.php
- core/Util/Url.php
- core/Util/util.php
- ext/biography/main.php
- ext/danbooru_api/main.php
- ext/featured/main.php
- ext/home/main.php
- ext/image/main.php
- ext/media/main.php
- ext/ouroboros_api/main.php
- ext/setup/main.php
- ext/static_files/main.php
- ext/statsd/main.php
- ext/user/main.php
- ext/wiki/main.php
- tests/bootstrap.php
- themes/lite/page.class.php
being able to set a default in `get()` made it possible for multiple callsites to request the same config and get different values
> [various] Avoid redundant usage of config defaults

- core/Config/Config.php
- core/Config/ConfigTest.php
- ext/cron_uploader/main.php
- ext/filter/theme.php
being able to set a default in `get()` made it possible for multiple callsites to request the same config and get different values
> [core] Remove default param from config->get_XXX()

- core/User/UserClass.php
- core/User/UserClassSource.php
- ext/perm_manager/main.php
This is going to become useful with a class editor, where default / file / database classes need to be edited differently
> [perm-manager] Keep track of where classes came from

- ext/tag_categories/theme.php
Found this bug on latest changes on main, so here's a PR that restores the functionality of editing/adding new tag categories!
Repro steps:
- Clone shimmie2 from main branch
- Run shimmie2
- Install Tag Categories extension
- Navigate to the "Tag Categories" page (tags/categories)
- Try to edit an existing tag from the defaults
- Button will be unresponsive due to a "SyntaxError" on the "Edit" button.
- Try to create a new Tag Category
- Button will be unresponsive as the "Submit" button is outside of the new Tag Category form
> Fix Submit button for Edit Tag Category / Submit button for New Tag Category

- core/Page/Page.php
- core/Page/PageMode.php
- core/Testing/ShimmiePHPUnitTestCase.php
- index.php
The default implementation of `display_error()` being to remove any existing Blocks, add a new Block with an error message, and then do the same stuff that `display_page()` does
```
protected function display_error(): void
{
$error = $this->error;
assert($error !== null);
$this->set_code($error->http_code);
$this->set_title("Error");
$this->blocks = [];
$this->add_block(new Block(null, \MicroHTML\SPAN($error->getMessage())));
$this->display_page();
}
```
> [core] Make a specific function for Page::display_error() so that themes can override it

- ext/bulk_add_csv/main.php
I honestly have no idea what I was doing with this one. Changes courtesy of ChatGPT. They appear to work whereas before I was receiving an error. ChatGPT thought it was cut-and-dry and that this still follows the goals of alpha.
This was the error I was receiving prior to this edit:
```Internal Error
Message: TypeError: Shimmie2\BulkAddCSV::add_image(): Argument #1 ($tmpname) must be of type Shimmie2\Path, string given, called in /mnt/booksimagesmusic/shimmie2/ext/bulk_add_csv/main.php on line 105
Version: 2.12.0-alpha-git (on 8.4.6)
Stack Trace:
#0 /mnt/booksimagesmusic/shimmie2/ext/bulk_add_csv/main.php(105): Shimmie2\BulkAddCSV->add_image()
#1 /mnt/booksimagesmusic/shimmie2/ext/bulk_add_csv/main.php(22): Shimmie2\BulkAddCSV->add_csv()
#2 …
```
> Update main.php for ext bulk_add_csv

- themes/danbooru2/style.css
Changes block at line 133:
BODY.layout-grid {
display: grid;
grid-template-columns: 11.5rem auto;
grid-gap: 0 2rem;
}
to:
BODY.layout-grid {
display: grid;
grid-template-columns: 11.5rem auto;
grid-gap: 0 4rem;
}
This fixes some overlap between the main body and the navigation sidebar. I considered reducing the padding on the navigation bar itself but that made it misalign with the top navigation bar text. I haven't yet seen any page issues with this change.
2 screenshots showing the difference are attached. I have tested this at 1440p, 4k and on mobile.
> [themes] Update danbooru2 style.css

- ext/notes/main.php
- Fixes typo in regex for detecting a comparative `notes:` search
- Updates image note count when deleting, nuking and reverting
- Excludes disabled (deleted) notes from count
> [notes] fix note count

- ext/image/main.php
Fixes permission check to show the delete button to users only able to delete specific images. I didn't realize this line wasn't updated ^^
> [image] show delete button if user can delete own image

- core/ImageBoard/Tag.php
- ext/post_tags/config.php
- ext/post_tags/main.php
Based on #1843 by discomrade, but being a part of the post_tags extension rather than being a separate thing
> [post_tags] option to force tags to lowercase
